datasets:
  abalone:
    task: regression
  winequality:
    task: regression
  diabetes:
    task: regression

  adult:
    task: classification
  bank_marketing:
    task: classification
  breast_cancer:
    task: classification
  credit:
    task: classification
  heart:
    task: classification
  ionosphere:
    task: classification
  sonar:
    task: classification

test_size: 0.2
single_seed: 42
multi_seeds: 50
cv_folds: 5
cv_repeats: 10


